### ISSUE TITLE
Issue with installing pip requirements

### ISSUE THREAD

**Issue by ccsavvy** [ninjakx/youtube-video2ppt#1]
Hi, first of all thank you for this awesome tool! However, I have a problem configuring and make it work. As screenshot attached. 

![image](https://user-images.githubusercontent.com/4044167/135811034-bdb40404-c0d0-4525-b1ac-b93667a1dff3.png)

Please advise. Thanks in advance

Cheers!

**Comment by ninjakx** [comment]
Hi @ccsavvy Thanks for reporting the issue. :) 

It seems you are facing issue related to `f-string` can you tell which python version you are using? 
It works for python 3.6+ .

I tested on my system (linux):

![Screenshot from 2021-10-04 13-34-49](https://user-images.githubusercontent.com/29797787/135815334-0735392d-03a2-4e7c-ade0-ebfc06adf43c.png)

**Comment by ccsavvy** [comment]
Hey @ninjakx I always like to help things improve ;) 

I'm using version Python 2.7.16. 

Will try to install Python 3.6 and let you know :D 

Thank you very much!

**Comment by ccsavvy** [comment]
Hey, I got it now. Haha I just have to sort things out on MacOS ❤️ 

![image](https://user-images.githubusercontent.com/4044167/135837010-270c696c-4a23-43d0-b47d-ed1ad07ce0b8.png)
